name: lint test deploy workflow
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checks code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npx eslint 

    - name: build project
      run: npn run build
